# If enabled, players will be able to get the enchantments (Not the Items) through the enchanting Table.
enchantmentTable: enabled
enchantmentTableProbability: 5
commandBypass: false
AntiMcMMOrepair: false
restrictEnchantments: false
maximumEnchants: 1
#
enchantments:
 lore:
# Set the look of the Lore-Enchantments
   disableItalic: false
   color: DARK_RED
# Enables/Disables the use of permissions.
 requirePermissions: false
#
 Autorepair:
  enabled: true
  enchantProbability: 1
  healAmount: 1
  stopAtFullDur: true
  repairOnMoving: false
#
 Blind:
  enabled: true
  enchantProbability: 1
# Sets the Strength and Duration of the Weakness + Blind Potioneffects.
  strength: 10
  duration: 2
#
 BlindBow:
  enabled: true
  enchantProbability: 1
#
 Block:
  enabled: true
  enchantProbability: 1
# The Cooldown after the player has stopped blocking
  cooldown: 20
# Sets the Strength and Duration of the Protection Potioneffect.
  strength: 5
  duration: 1
#
 BombardmentBow:
  enabled: true
  enchantProbability: 1
#
 Cripple:
  enabled: true
  enchantProbability: 1
#
 Cursed:
  enabled: true
  enchantProbability: 1
#
 Deathbringer:
  enabled: true
  enchantProbability: 1
# Sets the damage multiplier
  damageAmplifier: 2
#
 Deepwounds:
  enabled: true
  bleedChance: 25
  enchantProbability: 1
#
 Enlighted:
  enabled: true
  enchantProbability: 1
# The Duration and Strength of Regeneration applied to the wearer by the Enlighted armor
  Duration: 2
  Strength: 3
#
 FireworkBow:
  enabled: true
  enchantProbability: 1
# Sets the Duration of the Arrow shooting Fireworks
  Duration: 5
# Sets the Delay between Fireworks being shot in ticks // 1 Second = 20 Ticks
  Delay: 1
#
 Frozen:
  enabled: true
  enchantProbability: 1
# The Duration and Strength of Slowness applied to an enemy by the Frozen armor
  Duration: 4
  Strength: 5
#
 Gears:
  enabled: true
  enchantProbability: 1
  speedBoost: 3
#
 Glowing:
  enabled: true
  enchantProbability: 1
#
 Gooey:
  enabled: true
  enchantProbability: 1
# Decides wether Gooey is used by hitting an enemy or by rightclicking an enemy.
  heightMultiplier: 1.5
  rightclick: false
#
 Hardened:
  enabled: true
  enchantProbability: 1
# The Duration and Strength of Weakness applied to an enemy by the Hardened armor
  Duration: 1
  Strength: 5
#
 Hooks:
  enabled: true
  enchantProbability: 1
#
 Ice:
  enabled: true
  enchantProbability: 1
# Enables/Disables the Ice-Prison Effect
  specialFreeze: true
#
 Implants:
  enabled: true
  enchantProbability: 1
#
 LightningBow:
  enabled: true
  enchantProbability: 1
# Custom Lightning will only display the effect of a Lightning, it will not cause fire and damage will be applied customly
  customLightning: false
#
 Lifesteal:
  enabled: true
  enchantProbability: 1
# Indicates how much a hit will heal in half hearts
  heal: 1
#
 Molten:
  enabled: true
  enchantProbability: 1
# The Duration of the fire applied to an enemy by Molten armor
  Duration: 2
#
 Obsidianshielding:
  enabled: true
  enchantProbability: 1
#
 Poison:
  enabled: true
  enchantProbability: 1
# Sets the Strength and Duration of the Poison.
  strength: 6
  duration: 1
#
 PoisonBow:
  enabled: true
  enchantProbability: 1
# Sets the Duration and the Strength of the Poison applied by the Poison Bow enchantment
  Duration: 8
  Strength: 4
#
 Poisoned:
  enabled: true
  enchantProbability: 1
# The Duration and Strength of Poison applied to an enemy by the Poisoned armor
  Duration: 2
  Strength: 5
#
 Shockwave:
  enabled: true
  enchantProbability: 1
  cooldown: 5
#
 Stomp:
  enabled: true
  enchantProbability: 1
#
 Springs:
  enabled: true
  enchantProbability: 1
  jumpBoost: 3
#
 Thunderingblow:
  enabled: true
  lightningChance: 25
#
 Vampire:
  enabled: true
  enchantProbability: 1
#
#
#
items:
 Assassin:
  enabled: true
# The Length of the Invisibility after hitting an enemy.
  Length(Attack): 1
# The Cooldown of the Invisibility of hitting someone
  Cooldown(Attack): 3
# The Length of the Invisibility after rightclicking.
  Length(Use): 3
# The Cooldown after rightclicking with the sword.
  Cooldown(Use): 10
# The length of the Weakness after Stabbing a Player. Stabbing = Hitting an Enemy while Invisible
  WeaknessLength: 10
#
 Bandage:
  enabled: true
# The Cooldown when used on oneself
  Cooldown(Self): 60
# The Cooldown when used on others
  Cooldown(Others): 30
#
 BeastmastersBow:
  enabled: true
# The type of mob to spawn, found under http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/EntityType.html
  toSpawn: ZOMBIE
# Amount of mobs to spawn
  mobAmount: 3
#
 Deathscythe:
  enabled: true
  cooldown: 10
# The range of the Grab
  range: 10
# The Duration and Strength of the Wither debuff applied
  debuffDuration: 3
  debuffStrength: 1
#
 Flamethrower:
  enabled: true
# Determines wether or not the Flamethrower can be reloaded
  isReloadable: true
# The Time an entity stays on fire
  fireDuration: 3
#
 HermesBoots:
  enabled: true
# The Strength of the speedbuff applied by the Hermes Boots
  speedStrength: 2
#
 HookshotBow:
  enabled: true
#
 Landmine:
  enabled: true
# Cooldown after having failed disarming a Landmine
  disarmCooldown: 20
#
 LivefireBoots:
  enabled: true
# The Duration the flames will stay
  flameDuration: 2
#
 Medikit:
  enabled: true
  cooldown: 60
#
 Minigun:
  enabled: true
# The amount of shots fired per burst
  shotsFired: 20
#
 NecromancerStaff:
  enabled: true
# The Redstone costs per Spell
  Cost(Wither): 10
  Cooldown(Wither): 2
  Cost(Fireball): 4
  Cooldown(Fireball): 1
  Cost(Lightning): 20
  Cooldown(Lightning): 2
#
 Potionlauncher:
  enabled: true
#
 Powergloves:
  enabled: true
# The cooldown after having used the Gloves.
  Cooldown: 5
# The amount of time an Object can be held in Hand.
  MaxGrabtime: 3
  ThrowStrength: 2
#
 PyroAxe:
  enabled: true
# The amount the damage is multiplied by
  damageMultiplier: 3
#
 RocketBoots:
  enabled: true
#
 Suicidelever:
  enabled: true
  strength: 10
  tntAmount: 1
#
 Swimsuit:
  enabled: true
  damageBoostUnderwater: 2
  speedBoostUnderwater: 4
#
 ThorsAxe:
  enabled: true
# The cooldown between each use
  Cooldown: 10
# The amount of Time the Fire will stay
  fireDuration: 5
